### PR TITLE
0.7 updates merged

### PR DESCRIPTION
**Pull request by codygman**
This is a combination of #33 and #31. @sharkdp said he was going on vacation and said to feel free to merge our changes together.

This is compiling with psc 0.7.0.0. Here is a test of everything cloning my repo and it's changes from scratch:

```shell
cody@cody-G46VW:/tmp$ git clone git@github.com:codygman/purescript-simple-dom.git
Cloning into 'purescript-simple-dom'...
remote: Counting objects: 1090, done.        
remote: Compressing objects: 100% (74/74), done.        
remote: Total 1090 (delta 39), reused 0 (delta 0), pack-reused 995        
Receiving objects: 100% (1090/1090), 161.43 KiB | 0 bytes/s, done.
Resolving deltas: 100% (504/504), done.
Checking connectivity... done.
cody@cody-G46VW:/tmp$ cd purescript-simple-dom/
cody@cody-G46VW:/tmp/purescript-simple-dom$ git checkout 0.7-updates-merged
Branch 0.7-updates-merged set up to track remote branch 0.7-updates-merged from origin.
Switched to a new branch '0.7-updates-merged'
cody@cody-G46VW:/tmp/purescript-simple-dom$ npm install; bower update; gulp
> spawn-sync@1.0.11 postinstall /tmp/purescript-simple-dom/node_modules/gulp-purescript/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

rimraf@2.4.1 node_modules/rimraf
└── glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)

gulp-plumber@1.0.1 node_modules/gulp-plumber
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, beeper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.5.0, chalk@1.1.0, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)

gulp-purescript@0.5.0-rc.1 node_modules/gulp-purescript
├── minimist@1.1.1
├── resolve-bin@0.3.0 (find-parent-dir@0.1.0)
├── which@1.1.1 (is-absolute@0.1.7)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── logalot@2.1.0 (figures@1.3.5, squeak@1.2.0)
├── glob@5.0.12 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
├── multipipe@0.1.2 (duplexer2@0.0.2)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.0, chalk@1.1.0, lodash.template@3.6.2, through2@2.0.0, dateformat@1.0.11)
└── cross-spawn@0.4.1 (lru-cache@2.6.5, spawn-sync@1.0.11)

gulp@3.9.0 node_modules/gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.2
├── deprecated@0.0.1
├── archy@1.0.0
├── tildify@1.1.0 (os-homedir@1.0.0)
├── minimist@1.1.1
├── v8flags@2.0.9 (user-home@1.1.1)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── semver@4.3.6
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, beeper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.0, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.1, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

gulp-run@1.6.8 node_modules/gulp-run
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.5.0, chalk@1.1.0, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── lodash@3.10.0

gulp-jscs@1.6.0 node_modules/gulp-jscs
├── object-assign@2.1.1
├── tildify@1.1.0 (os-homedir@1.0.0)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, beeper@1.1.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.5.0, chalk@1.1.0, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── jscs@1.13.1 (strip-json-comments@1.0.2, pathval@0.1.1, commander@2.6.0, estraverse@1.9.3, vow@0.4.10, exit@0.1.2, chalk@1.0.0, glob@5.0.12, lodash.assign@3.0.0, cli-table@0.3.1, minimatch@2.0.8, vow-fs@0.3.4, esprima-harmony-jscs@1.1.0-bin, esprima@1.2.5, prompt@0.2.14, xmlbuilder@2.6.4)

gulp-jshint@1.11.1 node_modules/gulp-jshint
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.1.1, vinyl@0.5.0, chalk@1.1.0, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
├── rcloader@0.1.2 (rcfinder@0.1.8, lodash@2.4.2)
├── lodash@3.10.0
└── jshint@2.8.0 (strip-json-comments@1.0.2, exit@0.1.2, console-browserify@1.1.0, shelljs@0.3.0, cli@0.6.6, htmlparser2@3.8.3, lodash@3.7.0)
bower cached        git://github.com/joneshf/purescript-dom.git#0.1.2
bower validate      0.1.2 against git://github.com/joneshf/purescript-dom.git#^0.1.0
bower cached        git://github.com/purescript/purescript-arrays.git#0.4.0
bower validate      0.4.0 against git://github.com/purescript/purescript-arrays.git#^0.4.0
bower cached        git://github.com/purescript/purescript-maybe.git#0.3.0
bower validate      0.3.0 against git://github.com/purescript/purescript-maybe.git#^0.3.0
bower cached        git://github.com/purescript/purescript-foldable-traversable.git#0.4.0
bower validate      0.4.0 against git://github.com/purescript/purescript-foldable-traversable.git#^0.4.0
bower cached        git://github.com/purescript/purescript-tuples.git#0.4.0
bower validate      0.4.0 against git://github.com/purescript/purescript-tuples.git#^0.4.0
bower cached        git://github.com/purescript/purescript-strings.git#0.5.0
bower validate      0.5.0 against git://github.com/purescript/purescript-strings.git#^0.5.0
bower cached        git://github.com/purescript/purescript-sets.git#0.4.0
bower validate      0.4.0 against git://github.com/purescript/purescript-sets.git#^0.4.0
bower cached        git://github.com/purescript/purescript-math.git#0.2.0
bower validate      0.2.0 against git://github.com/purescript/purescript-math.git#^0.2.0
bower cached        git://github.com/purescript/purescript-quickcheck.git#0.6.0
bower validate      0.6.0 against git://github.com/purescript/purescript-quickcheck.git#^0.6.0
bower cached        git://github.com/purescript/purescript-st.git#0.1.0
bower validate      0.1.0 against git://github.com/purescript/purescript-st.git#^0.1.0
bower cached        git://github.com/purescript-contrib/purescript-bifunctors.git#0.4.0
bower validate      0.4.0 against git://github.com/purescript-contrib/purescript-bifunctors.git#^0.4.0
bower cached        git://github.com/purescript/purescript-monoid.git#0.3.0
bower validate      0.3.0 against git://github.com/purescript/purescript-monoid.git#^0.3.0
bower cached        git://github.com/purescript/purescript-maps.git#0.4.0
bower validate      0.4.0 against git://github.com/purescript/purescript-maps.git#^0.4.0
bower cached        git://github.com/purescript/purescript-random.git#0.2.0
bower validate      0.2.0 against git://github.com/purescript/purescript-random.git#^0.2.0
bower cached        git://github.com/purescript/purescript-exceptions.git#0.3.0
bower validate      0.3.0 against git://github.com/purescript/purescript-exceptions.git#^0.3.0
bower cached        git://github.com/paf31/purescript-lists.git#0.7.0
bower validate      0.7.0 against git://github.com/paf31/purescript-lists.git#^0.7.0
bower cached        git://github.com/purescript/purescript-either.git#0.2.0
bower validate      0.2.0 against git://github.com/purescript/purescript-either.git#^0.2.0
bower cached        git://github.com/purescript/purescript-console.git#0.1.0
bower validate      0.1.0 against git://github.com/purescript/purescript-console.git#^0.1.0
bower cached        git://github.com/purescript/purescript-eff.git#0.1.0
bower validate      0.1.0 against git://github.com/purescript/purescript-eff.git#^0.1.0
bower cached        git://github.com/purescript/purescript-control.git#0.3.0
bower validate      0.3.0 against git://github.com/purescript/purescript-control.git#^0.3.0
bower cached        git://github.com/purescript/purescript-invariant.git#0.3.0
bower validate      0.3.0 against git://github.com/purescript/purescript-invariant.git#^0.3.0
bower cached        git://github.com/purescript/purescript-integers.git#0.2.0
bower validate      0.2.0 against git://github.com/purescript/purescript-integers.git#^0.2.0
bower cached        git://github.com/purescript/purescript-prelude.git#0.1.0
bower validate      0.1.0 against git://github.com/purescript/purescript-prelude.git#^0.1.0
bower cached        git://github.com/purescript/purescript-functions.git#0.1.0
bower validate      0.1.0 against git://github.com/purescript/purescript-functions.git#^0.1.0
bower cached        git://github.com/purescript/purescript-lazy.git#0.4.0
bower validate      0.4.0 against git://github.com/purescript/purescript-lazy.git#^0.4.0
bower cached        git://github.com/paf31/purescript-unfoldable.git#0.4.0
bower validate      0.4.0 against git://github.com/paf31/purescript-unfoldable.git#^0.4.0
bower install       purescript-arrays#0.4.0
bower install       purescript-foldable-traversable#0.4.0
bower install       purescript-maybe#0.3.0
bower install       purescript-dom#0.1.2
bower install       purescript-tuples#0.4.0
bower install       purescript-strings#0.5.0
bower install       purescript-sets#0.4.0
bower install       purescript-math#0.2.0
bower install       purescript-quickcheck#0.6.0
bower install       purescript-st#0.1.0
bower install       purescript-bifunctors#0.4.0
bower install       purescript-monoid#0.3.0
bower install       purescript-maps#0.4.0
bower install       purescript-random#0.2.0
bower install       purescript-exceptions#0.3.0
bower install       purescript-lists#0.7.0
bower install       purescript-either#0.2.0
bower install       purescript-console#0.1.0
bower install       purescript-eff#0.1.0
bower install       purescript-control#0.3.0
bower install       purescript-invariant#0.3.0
bower install       purescript-integers#0.2.0
bower install       purescript-prelude#0.1.0
bower install       purescript-functions#0.1.0
bower install       purescript-lazy#0.4.0
bower install       purescript-unfoldable#0.4.0

purescript-arrays#0.4.0 bower_components/purescript-arrays
├── purescript-foldable-traversable#0.4.0
├── purescript-st#0.1.0
└── purescript-tuples#0.4.0

purescript-foldable-traversable#0.4.0 bower_components/purescript-foldable-traversable
├── purescript-bifunctors#0.4.0
└── purescript-maybe#0.3.0

purescript-maybe#0.3.0 bower_components/purescript-maybe
└── purescript-monoid#0.3.0

purescript-dom#0.1.2 bower_components/purescript-dom

purescript-tuples#0.4.0 bower_components/purescript-tuples
└── purescript-foldable-traversable#0.4.0

purescript-strings#0.5.0 bower_components/purescript-strings
└── purescript-maybe#0.3.0

purescript-sets#0.4.0 bower_components/purescript-sets
├── purescript-arrays#0.4.0
├── purescript-foldable-traversable#0.4.0
├── purescript-maps#0.4.0
├── purescript-maybe#0.3.0
└── purescript-tuples#0.4.0

purescript-math#0.2.0 bower_components/purescript-math

purescript-quickcheck#0.6.0 bower_components/purescript-quickcheck
├── purescript-arrays#0.4.0
├── purescript-console#0.1.0
├── purescript-either#0.2.0
├── purescript-exceptions#0.3.0
├── purescript-foldable-traversable#0.4.0
├── purescript-lists#0.7.0
├── purescript-math#0.2.0
├── purescript-random#0.2.0
└── purescript-strings#0.5.0

purescript-st#0.1.0 bower_components/purescript-st
└── purescript-eff#0.1.0

purescript-bifunctors#0.4.0 bower_components/purescript-bifunctors
└── purescript-control#0.3.0

purescript-monoid#0.3.0 bower_components/purescript-monoid
├── purescript-control#0.3.0
└── purescript-invariant#0.3.0

purescript-maps#0.4.0 bower_components/purescript-maps
├── purescript-arrays#0.4.0
├── purescript-eff#0.1.0
├── purescript-foldable-traversable#0.4.0
├── purescript-functions#0.1.0
├── purescript-integers#0.2.0
├── purescript-lists#0.7.0
├── purescript-math#0.2.0
├── purescript-maybe#0.3.0
├── purescript-prelude#0.1.0
├── purescript-st#0.1.0
├── purescript-strings#0.5.0
└── purescript-tuples#0.4.0

purescript-random#0.2.0 bower_components/purescript-random
├── purescript-eff#0.1.0
├── purescript-integers#0.2.0
└── purescript-math#0.2.0

purescript-exceptions#0.3.0 bower_components/purescript-exceptions
└── purescript-eff#0.1.0

purescript-lists#0.7.0 bower_components/purescript-lists
├── purescript-foldable-traversable#0.4.0
├── purescript-lazy#0.4.0
└── purescript-unfoldable#0.4.0

purescript-either#0.2.0 bower_components/purescript-either
└── purescript-foldable-traversable#0.4.0

purescript-console#0.1.0 bower_components/purescript-console
└── purescript-eff#0.1.0

purescript-eff#0.1.0 bower_components/purescript-eff
└── purescript-prelude#0.1.0

purescript-control#0.3.0 bower_components/purescript-control
└── purescript-prelude#0.1.0

purescript-invariant#0.3.0 bower_components/purescript-invariant
└── purescript-prelude#0.1.0

purescript-integers#0.2.0 bower_components/purescript-integers
└── purescript-maybe#0.3.0

purescript-prelude#0.1.0 bower_components/purescript-prelude

purescript-functions#0.1.0 bower_components/purescript-functions
└── purescript-prelude#0.1.0

purescript-lazy#0.4.0 bower_components/purescript-lazy
└── purescript-monoid#0.3.0

purescript-unfoldable#0.4.0 bower_components/purescript-unfoldable
├── purescript-arrays#0.4.0
└── purescript-tuples#0.4.0
[20:06:34] Using gulpfile /tmp/purescript-simple-dom/gulpfile.js
[20:06:34] Starting 'lint'...
[20:06:34] Starting 'clean-docs'...
[20:06:34] Starting 'dotpsci'...
[20:06:34] Finished 'clean-docs' after 176 ms
[20:06:34] Starting 'docs'...
[20:06:35] Finished 'lint' after 481 ms
[20:06:35] Starting 'make'...
[20:06:35] Finished 'dotpsci' after 488 ms
[20:06:37] Finished 'docs' after 2.36 s
[20:06:43] Finished 'make' after 8.68 s
[20:06:43] Starting 'default'...
[20:06:43] Finished 'default' after 22 μs
```

### CODE REVIEW

**Comment by sharkdp** [comment]
:+1:

**Comment by paf31** [comment]
:+1: Yes please.

**Comment by aktowns** [comment]
Merging this in, thank you :) 

I haven't really had any time to do anything purescript in a while so wondering if anyone would be happy to take this over? happy to add others at collaborators to this repo if someone just wants to help manage PR's I'm not really doing it justice :(

**Comment by codygman** [comment]
I can help manage PRs from time to time.

- Cody

**Comment by wildlyinaccurate** [comment]
I noticed that the "test" task was (maybe accidentally?) removed with the Grunt -> Gulp switch. I don't have time to finish it right now but I've started restoring this task in #35, since I find the tests useful.

**Comment by codygman** [comment]
Oops, I don't remember doing that :S

Hope things work fine for you now.

**Pull request merged**
