### PR TITLE
Add appendChild

### PR DESCRIPTION
**Pull request by puffnfresh**

### CODE REVIEW

**Comment by jdegoes** [comment]
:+1:  :+1:  :fireworks: :+1:  :+1:

**Comment by paf31** [comment]
:+1: Yes, please.

**Comment by jdegoes** [comment]
@paf31 May be a good idea for a fork of this to live in contrib?

**Comment by puffnfresh** [comment]
@jdegoes :+1:

**Comment by aktowns** [comment]
Thank you! merged in and tagged to `0.0.2`

**Pull request merged**
